/* ==============================================================
   settings.js — RONwifi Portal Configuration
   
   This file is generated by the RONwifi backend admin dashboard
   and uploaded to MikroTik at /hotspot/settings.js
   
   During prototyping, edit this manually.
   ============================================================== */

window.RONWIFI_SETTINGS = {
  version: 1,
  generated_at: "2026-04-20T00:00:00Z",

  brand: {
    title: "RONwifi",
    announcement_enabled: true,
    announcement_text: "Please screenshot your receipt and don't share codes."
  },

  backend: {
    base_url: "http://10.99.0.8:8000",
    timeout_ms: 5000
  },

  features: {
    show_extend_button: true,
    voucher_enabled: true,
    points_enabled: true,
    telegram_enabled: true
  },

  telegram: {
    bot_token: "6196252549:AAEQEpwb6CzwaVWOlOr0aiBSyAwp4NBXPPk",
    events: {
      on_insert_coin: true,
      on_each_coin: true,
      on_done: true,
      on_voucher_redeem: true,
      on_points_redeem: true
    }
  },

  vendos: [
    {
      id: 1,
      name: "VENDOTEST",
      ip: "10.0.88.3",
      mac: "68:C6:3A:F5:62:5F",
      interface: "vlan88",
      telegram_chat_id: "-859651652",
      enabled: true
    }
  ]
};
